config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum state: {progress: 0, success: 1}
  validates :title, :detail, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :set_locale

  def set_locale(&action)
    locale = params[:locale]
    unless I18n.locale_available?(locale)
      locale = I18n.default_locale
    end
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    {locale: params[:locale]}
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos
  def index
    @todos = Todo.order(limit: "DESC")
  end

  # GET /todos/1
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to @todo, notice: I18n.t('todos.create.successfully_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
      redirect_to @todo, notice: I18n.t('todos.update.successfully_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    redirect_to todos_url, notice: I18n.t('todos.destroy.successfully_destroyed')
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :detail, :state, :limit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>TodoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <hr>
    Languages:
    <% I18n.available_locales.each do |locale| %>
      <%= link_to locale, todos_path(locale: locale) %>
    <% end %>
    <hr>
    <p>Copyright PJZ9n all rights reserved.</p>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', count: todo.errors.count, model: todo.model_name.human) %>:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, Todo.states_i18n.invert %>
  </div>

  <div class="field">
    <%= form.label :limit %>
    <%= form.date_select :limit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', todo: @todo %>

<%= link_to t('.show'), @todo %> |
<%= link_to t('.back'), todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>

<% if @todos.size > 0 %>
  <table>
    <thead>
      <tr>
        <th><%= Todo.human_attribute_name :title %></th>
        <th><%= Todo.human_attribute_name :detail %></th>
        <th><%= Todo.human_attribute_name :state %></th>
        <th><%= Todo.human_attribute_name :limit %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.title %></td>
          <td><%= todo.detail %></td>
          <td><%= todo.state_i18n %></td>
          <td><%= todo.limit %></td>
          <td><%= link_to t('.show'), todo %></td>
          <td><%= link_to t('.edit'), edit_todo_path(todo) %></td>
          <td><%= link_to t('.destroy'), todo, method: :delete, data: {confirm: t('.are_you_sure')} %></td>
          <% if todo.progress? %>
            <td><%= link_to t('.mark_success'), todo_path(todo, todo: {state: :success}), method: :put %></td>
          <% else %>
            <td><%= link_to t('.mark_progress'), todo_path(todo, todo: {state: :progress}), method: :put %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= t(".no_todos") %></p>
<% end %>

<br>

<%= link_to t('.new_todo'), new_todo_path %>

app/views/todos/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', todo: @todo %>

<%= link_to t('.back'), todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.title') %>:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong><%= t('.detail') %>:</strong>
  <%= @todo.detail %>
</p>

<p>
  <strong><%= t('.state') %>:</strong>
  <%= @todo.state_i18n %>
</p>

<p>
  <strong><%= t('.limit') %>:</strong>
  <%= @todo.limit %>
</p>

<%= link_to t('.edit'), edit_todo_path(@todo) %> |
<%= link_to t('.back'), todos_path %>